name: Update Pull Request Status

on:
  pull_request:
    types: [opened, closed, reopened, synchronize]
  


jobs:
  update_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch target branch changes
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Switch to target branch
        run: git checkout ${{ github.event.pull_request.base.ref }}

      - name: Merge changes from origin/target-branch
        run: git merge --ff-only origin/${{ github.event.pull_request.base.ref }}

      - name: Get PR number and state
        run: |
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          PR_STATE=$(jq --raw-output .action "$GITHUB_EVENT_PATH")
          PR_DESCRIPTION=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}" | jq -r '.body')
          
          if [ "$PR_STATE" == "opened" ]; then
            echo "PR $PR_NUMBER Status: Pending" > pull_request_status.md
            echo "Description: $PR_DESCRIPTION" >> pull_request_status.md
          elif [ "$PR_STATE" == "closed" ]; then
            PR_MERGED=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}" | jq -r '.merged')
            if [ "$PR_MERGED" == "true" ]; then
              echo "PR $PR_NUMBER Status: Completed" > pull_request_status.md
              echo "Description: $PR_DESCRIPTION" >> pull_request_status.md
            else
              echo "PR $PR_NUMBER Status: Pending (Closed without merge)" > pull_request_status.md
              echo "Description: $PR_DESCRIPTION" >> pull_request_status.md
            fi
          fi

      - name: Commit and push changes
        run: |
          git config user.email "amirsohel.as10@gmail.com"
          git config user.name "asb19"
          git add pull_request_status.md
          git commit -m "Update PR status with description"
          git push origin ${{ github.event.pull_request.base.ref }}
         
