name: Update Pull Request Status

on:
  pull_request:
    types: [opened, closed, reopened, synchronize]
    paths:
      - /**
  workflow_dispatch:


jobs:
  update_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR description
        run: |
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          PR_DESCRIPTION=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}" | jq -r '.body')

          echo "PR $PR_NUMBER Description: $PR_DESCRIPTION" > pull_request_status.md

          git config user.email "amirsohel.as10@gmail.com"
          git config user.name "asb19"
          git add pull_request_status.md
          git commit -m "Update PR status with description"
          git push origin HEAD:main
